// <copyright file="CloudVariables.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using CloudPrefs;

    /// <summary>
    /// Provides access to cloud variables registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudVariables
    {
        private static readonly CloudInt s_distanceTravelled = new CloudInt("DistanceTravelled", PersistenceType.Highest, 0);

        public static int DistanceTravelled
        {
            get { return s_distanceTravelled.Value; }
            set { s_distanceTravelled.Value = value; }
        }

        private static readonly CloudInt s_personalBestScore = new CloudInt("PersonalBestScore", PersistenceType.Highest, 0);

        public static int PersonalBestScore
        {
            get { return s_personalBestScore.Value; }
            set { s_personalBestScore.Value = value; }
        }

        private static readonly CloudInt s_longestTimeSurvived = new CloudInt("LongestTimeSurvived", PersistenceType.Highest, 0);

        public static int LongestTimeSurvived
        {
            get { return s_longestTimeSurvived.Value; }
            set { s_longestTimeSurvived.Value = value; }
        }

        private static readonly CloudBool s_hasFinishedTutorial = new CloudBool("HasFinishedTutorial", PersistenceType.Highest, false);

        public static bool HasFinishedTutorial
        {
            get { return s_hasFinishedTutorial.Value; }
            set { s_hasFinishedTutorial.Value = value; }
        }

        private static readonly CloudBool s_isMuted = new CloudBool("IsMuted", PersistenceType.Latest, false);

        public static bool IsMuted
        {
            get { return s_isMuted.Value; }
            set { s_isMuted.Value = value; }
        }
    }
}
