// <copyright file="CloudIDs.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
#if (UNITY_ANDROID || UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
    using Internal;
    using UnityEngine;
#endif
    /// <summary>
    /// Provides access to achievement- and leaderboard IDs registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudIDs
    {
        /// <summary>
        /// Contains properties that retrieves achievement IDs for the current platform.
        /// </summary>
        public static class AchievementIDs
        {
            public static string Score100
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Score100";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Score250
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Score250";
#else
                    return string.Empty;
#endif
                }
            }

            public static string CherryPicker
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "CherryPicker";
#else
                    return string.Empty;
#endif
                }
            }

            public static string CherryHarvester
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "CherryHarvester";
#else
                    return string.Empty;
#endif
                }
            }

            public static string CherryHoarder
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "CherryHoarder";
#else
                    return string.Empty;
#endif
                }
            }

            public static string MoreTheMerrier
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "MoreTheMerrier";
#else
                    return string.Empty;
#endif
                }
            }

            public static string RunnersAssemble
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "RunnersAssemble";
#else
                    return string.Empty;
#endif
                }
            }

            public static string SkilledDodger
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "SkilledDodger";
#else
                    return string.Empty;
#endif
                }
            }

            public static string ExpertDodger
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "ExpertDodger";
#else
                    return string.Empty;
#endif
                }
            }

            public static string CherryPie
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "CherryPie";
#else
                    return string.Empty;
#endif
                }
            }

            public static string CherryBomb
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "CherryBomb";
#else
                    return string.Empty;
#endif
                }
            }
        }

        /// <summary>
        /// Contains properties that retrieves leaderboard IDs for the current platform.
        /// </summary>
        public static class LeaderboardIDs
        {
            public static string HighScore
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "HighScore";
#else
                    return string.Empty;
#endif
                }
            }
        }
    }
}
