// <copyright file="CloudVariables.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using CloudPrefs;

    /// <summary>
    /// Provides access to cloud variables registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudVariables
    {
        private static readonly CloudInt s_unlockedVerticalSpeedLevel = new CloudInt("UnlockedVerticalSpeedLevel", PersistenceType.Highest, 1);

        public static int UnlockedVerticalSpeedLevel
        {
            get { return s_unlockedVerticalSpeedLevel.Value; }
            set { s_unlockedVerticalSpeedLevel.Value = value; }
        }

        private static readonly CloudInt s_unlockedBoostSpeedLevel = new CloudInt("UnlockedBoostSpeedLevel", PersistenceType.Highest, 1);

        public static int UnlockedBoostSpeedLevel
        {
            get { return s_unlockedBoostSpeedLevel.Value; }
            set { s_unlockedBoostSpeedLevel.Value = value; }
        }

        private static readonly CloudInt s_unlockedManaRegenLevel = new CloudInt("UnlockedManaRegenLevel", PersistenceType.Highest, 1);

        public static int UnlockedManaRegenLevel
        {
            get { return s_unlockedManaRegenLevel.Value; }
            set { s_unlockedManaRegenLevel.Value = value; }
        }

        private static readonly CloudInt s_unlockedManaAmountLevel = new CloudInt("UnlockedManaAmountLevel", PersistenceType.Highest, 1);

        public static int UnlockedManaAmountLevel
        {
            get { return s_unlockedManaAmountLevel.Value; }
            set { s_unlockedManaAmountLevel.Value = value; }
        }

        private static readonly CloudCurrencyInt s_wisdomPotions = new CloudCurrencyInt("WisdomPotions", 1, false);

        public static int WisdomPotions
        {
            get { return s_wisdomPotions.Value; }
            set { s_wisdomPotions.Value = value; }
        }

        private static readonly CloudCurrencyInt s_midasPotions = new CloudCurrencyInt("MidasPotions", 1, false);

        public static int MidasPotions
        {
            get { return s_midasPotions.Value; }
            set { s_midasPotions.Value = value; }
        }

        private static readonly CloudInt s_distanceRecord = new CloudInt("DistanceRecord", PersistenceType.Highest, 0);

        public static int DistanceRecord
        {
            get { return s_distanceRecord.Value; }
            set { s_distanceRecord.Value = value; }
        }

        private static readonly CloudInt s_totalDistanceTraveled = new CloudInt("TotalDistanceTraveled", PersistenceType.Highest, 0);

        public static int TotalDistanceTraveled
        {
            get { return s_totalDistanceTraveled.Value; }
            set { s_totalDistanceTraveled.Value = value; }
        }

        private static readonly CloudInt s_totalSecondsPlayed = new CloudInt("TotalSecondsPlayed", PersistenceType.Highest, 0);

        public static int TotalSecondsPlayed
        {
            get { return s_totalSecondsPlayed.Value; }
            set { s_totalSecondsPlayed.Value = value; }
        }
    }
}
