// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_distanceRecords = new UnifiedLeaderboard("DistanceRecords",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "DistanceRecords"
#endif
            );

        public static UnifiedLeaderboard DistanceRecords
        {
            get { return s_distanceRecords; }
        }

        private static readonly UnifiedLeaderboard s_biggestCoinEarners = new UnifiedLeaderboard("BiggestCoinEarners",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "BiggestCoinEarners"
#endif
            );

        public static UnifiedLeaderboard BiggestCoinEarners
        {
            get { return s_biggestCoinEarners; }
        }

        private static readonly UnifiedLeaderboard s_coinsCollectedInOneFlight = new UnifiedLeaderboard("CoinsCollectedInOneFlight",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "CoinsCollectedInOneFlight"
#endif
            );

        public static UnifiedLeaderboard CoinsCollectedInOneFlight
        {
            get { return s_coinsCollectedInOneFlight; }
        }
    }
}
