// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_gettingHearted = new UnifiedAchievement("GettingHearted",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "GettingHearted"
#endif
            );

        public static UnifiedAchievement GettingHearted
        {
            get { return s_gettingHearted; }
        }

        private static readonly UnifiedAchievement s_bubbleTrouble = new UnifiedAchievement("BubbleTrouble",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "BubbleTrouble"
#endif
            );

        public static UnifiedAchievement BubbleTrouble
        {
            get { return s_bubbleTrouble; }
        }

        private static readonly UnifiedAchievement s_kamelot = new UnifiedAchievement("Kamelot",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "Kamelot"
#endif
            );

        public static UnifiedAchievement Kamelot
        {
            get { return s_kamelot; }
        }

        private static readonly UnifiedAchievement s_squire = new UnifiedAchievement("Squire",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "Squire"
#endif
            );

        public static UnifiedAchievement Squire
        {
            get { return s_squire; }
        }

        private static readonly UnifiedAchievement s_knightErrant = new UnifiedAchievement("KnightErrant",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "KnightErrant"
#endif
            );

        public static UnifiedAchievement KnightErrant
        {
            get { return s_knightErrant; }
        }

        private static readonly UnifiedAchievement s_paladin = new UnifiedAchievement("Paladin",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "Paladin"
#endif
            );

        public static UnifiedAchievement Paladin
        {
            get { return s_paladin; }
        }

        private static readonly UnifiedAchievement s_bucketChivalry = new UnifiedAchievement("BucketChivalry",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "BucketChivalry"
#endif
            );

        public static UnifiedAchievement BucketChivalry
        {
            get { return s_bucketChivalry; }
        }

        private static readonly UnifiedAchievement s_questingKnight = new UnifiedAchievement("QuestingKnight",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "QuestingKnight"
#endif
            );

        public static UnifiedAchievement QuestingKnight
        {
            get { return s_questingKnight; }
        }

        private static readonly UnifiedAchievement s_unstoppableRafter = new UnifiedAchievement("UnstoppableRafter",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "UnstoppableRafter"
#endif
            );

        public static UnifiedAchievement UnstoppableRafter
        {
            get { return s_unstoppableRafter; }
        }

        private static readonly UnifiedAchievement s_treasureHunter = new UnifiedAchievement("TreasureHunter",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "TreasureHunter"
#endif
            );

        public static UnifiedAchievement TreasureHunter
        {
            get { return s_treasureHunter; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_gettingHearted,
            s_bubbleTrouble,
            s_kamelot,
            s_squire,
            s_knightErrant,
            s_paladin,
            s_bucketChivalry,
            s_questingKnight,
            s_unstoppableRafter,
            s_treasureHunter,
        };
    }
}
