// <copyright file="CloudVariables.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using CloudPrefs;

    /// <summary>
    /// Provides access to cloud variables registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudVariables
    {
        private static readonly CloudInt s_highScore = new CloudInt("HighScore", PersistenceType.Highest, 0);

        public static int HighScore
        {
            get { return s_highScore.Value; }
            set { s_highScore.Value = value; }
        }

        private static readonly CloudInt s_totalCoinsAllTime = new CloudInt("TotalCoinsAllTime", PersistenceType.Highest, 0);

        public static int TotalCoinsAllTime
        {
            get { return s_totalCoinsAllTime.Value; }
            set { s_totalCoinsAllTime.Value = value; }
        }

        private static readonly CloudCurrencyInt s_totalCoins = new CloudCurrencyInt("TotalCoins", 0, false);

        public static int TotalCoins
        {
            get { return s_totalCoins.Value; }
            set { s_totalCoins.Value = value; }
        }

        private static readonly CloudInt s_numberOfPowerupsUnlocked = new CloudInt("NumberOfPowerupsUnlocked", PersistenceType.Highest, 0);

        public static int NumberOfPowerupsUnlocked
        {
            get { return s_numberOfPowerupsUnlocked.Value; }
            set { s_numberOfPowerupsUnlocked.Value = value; }
        }

        private static readonly CloudInt s_powerUpSlotOne = new CloudInt("PowerUpSlotOne", PersistenceType.Latest, 0);

        public static int PowerUpSlotOne
        {
            get { return s_powerUpSlotOne.Value; }
            set { s_powerUpSlotOne.Value = value; }
        }

        private static readonly CloudInt s_powerUpSlotTwo = new CloudInt("PowerUpSlotTwo", PersistenceType.Latest, 0);

        public static int PowerUpSlotTwo
        {
            get { return s_powerUpSlotTwo.Value; }
            set { s_powerUpSlotTwo.Value = value; }
        }
    }
}
