// <copyright file="CloudIDs.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
#if (UNITY_ANDROID || UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
    using Internal;
    using UnityEngine;
#endif
    /// <summary>
    /// Provides access to achievement- and leaderboard IDs registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudIDs
    {
        /// <summary>
        /// Contains properties that retrieves achievement IDs for the current platform.
        /// </summary>
        public static class AchievementIDs
        {
            public static string GettingHearted
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "GettingHearted";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BubbleTrouble
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "BubbleTrouble";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Kamelot
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Kamelot";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Squire
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Squire";
#else
                    return string.Empty;
#endif
                }
            }

            public static string KnightErrant
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "KnightErrant";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Paladin
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Paladin";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BucketChivalry
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "BucketChivalry";
#else
                    return string.Empty;
#endif
                }
            }

            public static string QuestingKnight
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "QuestingKnight";
#else
                    return string.Empty;
#endif
                }
            }

            public static string UnstoppableRafter
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "UnstoppableRafter";
#else
                    return string.Empty;
#endif
                }
            }

            public static string TreasureHunter
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "TreasureHunter";
#else
                    return string.Empty;
#endif
                }
            }
        }

        /// <summary>
        /// Contains properties that retrieves leaderboard IDs for the current platform.
        /// </summary>
        public static class LeaderboardIDs
        {
            public static string HighScores
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_AMAZON
                    return "";
#elif CLOUDONCE_GOOGLE
                    return "";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "HighScores";
#else
                    return string.Empty;
#endif
                }
            }
        }
    }
}
